### ISSUE TITLE
The termguicolors option must be set

### ISSUE THREAD

**Issue by linn8** [DavidBachmann/vim-punk-colorscheme#1]
I keep getting the error
"The termguicolors option must be set
Be aware macOS default Vim is broken, use Homebrew Vim instead
Press ENTER or type command to continue"
I tried "set termguicolors" in my vimrc, now the theme works but that error keeps showing. How can I fix that? I really like this theme btw

**Comment by DavidBachmann** [comment]
Hi linn8, glad you like it.

The default MacOS Vim binary has broken _termguicolors_. I recommend using [neovim](https://github.com/neovim/neovim) or at least installing a newer Vim version with [Homebrew](https://brew.sh/).

**Comment by linn8** [comment]
I deleted echomsg lines. it's fine now. thanks
